[variables]
PORT = "3000"
NODE_VERSION = "20"

[phases.setup]
nixPkgs = []

[phases.install]
cmds = ["npm ci --no-audit --prefer-offline"]

[phases.build] 
cmds = ["npm run build"]

[start]
cmd = "npx serve dist -l 3000"
